// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.4
// source: api/device_config_store.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DeviceConfigStoreService_Set_FullMethodName                      = "/api.DeviceConfigStoreService/Set"
	DeviceConfigStoreService_Get_FullMethodName                      = "/api.DeviceConfigStoreService/Get"
	DeviceConfigStoreService_Delete_FullMethodName                   = "/api.DeviceConfigStoreService/Delete"
	DeviceConfigStoreService_List_FullMethodName                     = "/api.DeviceConfigStoreService/List"
	DeviceConfigStoreService_GetDeviceConfigAlignment_FullMethodName = "/api.DeviceConfigStoreService/GetDeviceConfigAlignment"
	DeviceConfigStoreService_GetDeviceCurrentParams_FullMethodName   = "/api.DeviceConfigStoreService/GetDeviceCurrentParams"
)

// DeviceConfigStoreServiceClient is the client API for DeviceConfigStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceConfigStoreServiceClient interface {
	// Set configuration store for the device (i.e., Upsert).
	Set(ctx context.Context, in *SetDeviceConfigStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get returns the configuration store for the given DevEUI.
	Get(ctx context.Context, in *GetDeviceConfigStoreRequest, opts ...grpc.CallOption) (*GetDeviceConfigStoreResponse, error)
	// Delete removes the configuration store for the device.
	// Note: Configurations fall back to the regional default / ADR.
	Delete(ctx context.Context, in *DeleteDeviceConfigStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List DevEUIs of devices having configuration store.
	List(ctx context.Context, in *ListDeviceConfigStoresRequest, opts ...grpc.CallOption) (*ListDeviceConfigStoresResponse, error)
	// Returns the device's alignment status for stored configurations
	// (whether they have been sent to and acknowledged by the device).
	GetDeviceConfigAlignment(ctx context.Context, in *GetDeviceConfigAlignmentRequest, opts ...grpc.CallOption) (*GetDeviceConfigAlignmentResponse, error)
	// Get the MAC layer transmission parameters currently in use by the given device as far
	// as the server knows, based on most recent transmissions and MAC command acknowledgments.
	// Note: Params may not yet be aligned with the ones set in the device's config store.
	GetDeviceCurrentParams(ctx context.Context, in *GetDeviceCurrentParamsRequest, opts ...grpc.CallOption) (*GetDeviceCurrentParamsResponse, error)
}

type deviceConfigStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceConfigStoreServiceClient(cc grpc.ClientConnInterface) DeviceConfigStoreServiceClient {
	return &deviceConfigStoreServiceClient{cc}
}

func (c *deviceConfigStoreServiceClient) Set(ctx context.Context, in *SetDeviceConfigStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeviceConfigStoreService_Set_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceConfigStoreServiceClient) Get(ctx context.Context, in *GetDeviceConfigStoreRequest, opts ...grpc.CallOption) (*GetDeviceConfigStoreResponse, error) {
	out := new(GetDeviceConfigStoreResponse)
	err := c.cc.Invoke(ctx, DeviceConfigStoreService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceConfigStoreServiceClient) Delete(ctx context.Context, in *DeleteDeviceConfigStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeviceConfigStoreService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceConfigStoreServiceClient) List(ctx context.Context, in *ListDeviceConfigStoresRequest, opts ...grpc.CallOption) (*ListDeviceConfigStoresResponse, error) {
	out := new(ListDeviceConfigStoresResponse)
	err := c.cc.Invoke(ctx, DeviceConfigStoreService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceConfigStoreServiceClient) GetDeviceConfigAlignment(ctx context.Context, in *GetDeviceConfigAlignmentRequest, opts ...grpc.CallOption) (*GetDeviceConfigAlignmentResponse, error) {
	out := new(GetDeviceConfigAlignmentResponse)
	err := c.cc.Invoke(ctx, DeviceConfigStoreService_GetDeviceConfigAlignment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceConfigStoreServiceClient) GetDeviceCurrentParams(ctx context.Context, in *GetDeviceCurrentParamsRequest, opts ...grpc.CallOption) (*GetDeviceCurrentParamsResponse, error) {
	out := new(GetDeviceCurrentParamsResponse)
	err := c.cc.Invoke(ctx, DeviceConfigStoreService_GetDeviceCurrentParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceConfigStoreServiceServer is the server API for DeviceConfigStoreService service.
// All implementations must embed UnimplementedDeviceConfigStoreServiceServer
// for forward compatibility
type DeviceConfigStoreServiceServer interface {
	// Set configuration store for the device (i.e., Upsert).
	Set(context.Context, *SetDeviceConfigStoreRequest) (*emptypb.Empty, error)
	// Get returns the configuration store for the given DevEUI.
	Get(context.Context, *GetDeviceConfigStoreRequest) (*GetDeviceConfigStoreResponse, error)
	// Delete removes the configuration store for the device.
	// Note: Configurations fall back to the regional default / ADR.
	Delete(context.Context, *DeleteDeviceConfigStoreRequest) (*emptypb.Empty, error)
	// List DevEUIs of devices having configuration store.
	List(context.Context, *ListDeviceConfigStoresRequest) (*ListDeviceConfigStoresResponse, error)
	// Returns the device's alignment status for stored configurations
	// (whether they have been sent to and acknowledged by the device).
	GetDeviceConfigAlignment(context.Context, *GetDeviceConfigAlignmentRequest) (*GetDeviceConfigAlignmentResponse, error)
	// Get the MAC layer transmission parameters currently in use by the given device as far
	// as the server knows, based on most recent transmissions and MAC command acknowledgments.
	// Note: Params may not yet be aligned with the ones set in the device's config store.
	GetDeviceCurrentParams(context.Context, *GetDeviceCurrentParamsRequest) (*GetDeviceCurrentParamsResponse, error)
	mustEmbedUnimplementedDeviceConfigStoreServiceServer()
}

// UnimplementedDeviceConfigStoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceConfigStoreServiceServer struct {
}

func (UnimplementedDeviceConfigStoreServiceServer) Set(context.Context, *SetDeviceConfigStoreRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedDeviceConfigStoreServiceServer) Get(context.Context, *GetDeviceConfigStoreRequest) (*GetDeviceConfigStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDeviceConfigStoreServiceServer) Delete(context.Context, *DeleteDeviceConfigStoreRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDeviceConfigStoreServiceServer) List(context.Context, *ListDeviceConfigStoresRequest) (*ListDeviceConfigStoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDeviceConfigStoreServiceServer) GetDeviceConfigAlignment(context.Context, *GetDeviceConfigAlignmentRequest) (*GetDeviceConfigAlignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceConfigAlignment not implemented")
}
func (UnimplementedDeviceConfigStoreServiceServer) GetDeviceCurrentParams(context.Context, *GetDeviceCurrentParamsRequest) (*GetDeviceCurrentParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceCurrentParams not implemented")
}
func (UnimplementedDeviceConfigStoreServiceServer) mustEmbedUnimplementedDeviceConfigStoreServiceServer() {
}

// UnsafeDeviceConfigStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceConfigStoreServiceServer will
// result in compilation errors.
type UnsafeDeviceConfigStoreServiceServer interface {
	mustEmbedUnimplementedDeviceConfigStoreServiceServer()
}

func RegisterDeviceConfigStoreServiceServer(s grpc.ServiceRegistrar, srv DeviceConfigStoreServiceServer) {
	s.RegisterService(&DeviceConfigStoreService_ServiceDesc, srv)
}

func _DeviceConfigStoreService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceConfigStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceConfigStoreServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceConfigStoreService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceConfigStoreServiceServer).Set(ctx, req.(*SetDeviceConfigStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceConfigStoreService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceConfigStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceConfigStoreServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceConfigStoreService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceConfigStoreServiceServer).Get(ctx, req.(*GetDeviceConfigStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceConfigStoreService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceConfigStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceConfigStoreServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceConfigStoreService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceConfigStoreServiceServer).Delete(ctx, req.(*DeleteDeviceConfigStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceConfigStoreService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeviceConfigStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceConfigStoreServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceConfigStoreService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceConfigStoreServiceServer).List(ctx, req.(*ListDeviceConfigStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceConfigStoreService_GetDeviceConfigAlignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceConfigAlignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceConfigStoreServiceServer).GetDeviceConfigAlignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceConfigStoreService_GetDeviceConfigAlignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceConfigStoreServiceServer).GetDeviceConfigAlignment(ctx, req.(*GetDeviceConfigAlignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceConfigStoreService_GetDeviceCurrentParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceCurrentParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceConfigStoreServiceServer).GetDeviceCurrentParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceConfigStoreService_GetDeviceCurrentParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceConfigStoreServiceServer).GetDeviceCurrentParams(ctx, req.(*GetDeviceCurrentParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceConfigStoreService_ServiceDesc is the grpc.ServiceDesc for DeviceConfigStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceConfigStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.DeviceConfigStoreService",
	HandlerType: (*DeviceConfigStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _DeviceConfigStoreService_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DeviceConfigStoreService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DeviceConfigStoreService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DeviceConfigStoreService_List_Handler,
		},
		{
			MethodName: "GetDeviceConfigAlignment",
			Handler:    _DeviceConfigStoreService_GetDeviceConfigAlignment_Handler,
		},
		{
			MethodName: "GetDeviceCurrentParams",
			Handler:    _DeviceConfigStoreService_GetDeviceCurrentParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/device_config_store.proto",
}
